version: "3"

services:

  runtime-setup:
    image: netty:centos-7-1.19
    build:
      args:
        java_version : "19.0.1-zulu"

  build:
    image: netty:centos-7-1.19

  build-leak:
    image: netty:centos-7-1.19

  build-boringssl-static:
    image: netty:centos-7-1.19

  build-leak-boringssl-static:
    image: netty:centos-7-1.19

  shell:
    image: netty:centos-7-1.19
