version: "3"

services:

  runtime-setup:
    image: netty:centos-6-1.8
    build:
      args:
        centos_version : "6"
        java_version : "adopt@1.8.222-10"

  test:
    image: netty:centos-6-1.8
    volumes:
      - code-sync:/code:nocopy

  test-leak:
    image: netty:centos-6-1.8
    volumes:
      - code-sync:/code:nocopy

  test-boringssl-static:
    image: netty:centos-6-1.8
    volumes:
      - code-sync:/code:nocopy

  shell:
    image: netty:centos-6-1.8
    volumes:
      - code-sync:/code:nocopy

volumes:
  code-sync:
    external: true
