version: "3"

services:

  runtime-setup:
    image: netty:centos-6-1.11
    build:
      args:
        centos_version : "6"
        java_version : "adopt@1.11.0-9"

  test:
    image: netty:centos-6-1.11

  test-leak:
    image: netty:centos-6-1.11

  test-boringssl-static:
    image: netty:centos-6-1.11

  shell:
    image: netty:centos-6-1.11
