version: "3"

services:

  runtime-setup:
    image: netty:centos-6-1.11
    build:
      args:
        java_version : "adopt@1.11.0-11"

  build:
    image: netty:centos-6-1.11

  build-leak:
    image: netty:centos-6-1.11

  build-boringssl-static:
    image: netty:centos-6-1.11

  build-leak-boringssl-static:
    image: netty:centos-6-1.11

  shell:
    image: netty:centos-6-1.11

  partly-build-leak:
    image: netty:centos-6-1.11

  partly-build-leak-boringssl-static:
    image: netty:centos-6-1.11
