version: "3"

services:

  runtime-setup:
    image: netty-codec-quic-centos6:default
    build:
      context: ../
      dockerfile: docker/Dockerfile.centos6

  common: &common
    image: netty-codec-quic-centos6:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.m2/repository:/root/.m2/repository
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ..:/code:delegated
    working_dir: /code

  build:
    <<: *common
    command: /bin/bash -cl "mvn -Pci clean package"

  build-leak:
    <<: *common
    command: /bin/bash -cl "mvn -Pleak,ci clean package"

  build-clean:
    <<: *common
    command: /bin/bash -cl "mvn -Pci clean package"

  deploy:
    <<: *common
    command: /bin/bash -cl "mvn -Pci clean deploy -DskipTests=true"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2/repository:/root/.m2/repository
      - ~/.m2/settings.xml:/root/.m2/settings.xml
      - ..:/code

  deploy-clean:
    <<: *common
    command: /bin/bash -cl "mvn -Pci clean deploy -DskipTests=true"
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2/repository:/root/.m2/repository
      - ~/.m2/settings.xml:/root/.m2/settings.xml
      - ..:/code

  stage-snapshot:
    <<: *common
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2/settings.xml:/root/.m2/settings.xml
      - ~/.m2/repository:/root/.m2/repository
      - ~/local-staging:/root/local-staging
      - ..:/code
    command: /bin/bash -cl "mvn -Pci clean package org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DaltStagingDirectory=/root/local-staging -DskipRemoteStaging=true -DskipTests=true"

  stage-release:
    <<: *common
    environment:
      - GPG_KEYNAME
      - GPG_PASSPHRASE
      - GPG_PRIVATE_KEY
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.m2/settings.xml:/root/.m2/settings.xml
      - ~/.m2/repository:/root/.m2/repository
      - ~/local-staging:/root/local-staging
      - ..:/code
    command: /bin/bash -cl "cat <(echo -e \"${GPG_PRIVATE_KEY}\") | gpg --batch --import && mvn -B -Pci clean javadoc:jar package gpg:sign org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DnexusUrl=https://oss.sonatype.org -DserverId=sonatype-nexus-staging -DaltStagingDirectory=/root/local-staging -DskipRemoteStaging=true -DskipTests=true -Dgpg.passphrase=${GPG_PASSPHRASE} -Dgpg.keyname=${GPG_KEYNAME}"

  shell:
    <<: *common
    environment:
      - SONATYPE_USER
      - SONATYPE_PASSWORD
    volumes:
      - ~/.ssh:/root/.ssh:delegated
      - ~/.gnupg:/root/.gnupg:delegated
      - ~/.m2:/root/.m2:delegated
      - ~/.gitconfig:/root/.gitconfig:delegated
      - ~/.gitignore:/root/.gitignore:delegated
      - ..:/code:delegated
    entrypoint: /bin/bash
