version: "3"

services:

  runtime-setup:
    image: netty:centos-6-1.12
    build:
      args:
        centos_version : "6"
        java_version : "openjdk@1.12.0-19"

  test:
    image: netty:centos-6-1.12

  test-leak:
    image: netty:centos-6-1.12

  test-boringssl-static:
    image: netty:centos-6-1.12

  shell:
    image: netty:centos-6-1.12
