version: "3"

services:

  runtime-setup:
    image: netty:centos-6-1.13
    build:
      args:
        centos_version : "6"
        java_version : "openjdk@1.13.0-9"

  test:
    image: netty:centos-6-1.13

  test-leak:
    image: netty:centos-6-1.13

  test-boringssl-static:
    image: netty:centos-6-1.13

  shell:
    image: netty:centos-6-1.13
