version: "3"

services:

  runtime-setup:
    image: netty:centos-6-1.8
    build:
      args:
        java_version : "adopt@1.8.0-272"

  build:
    image: netty:centos-6-1.8

  build-leak:
    image: netty:centos-6-1.8

  build-boringssl-static:
    image: netty:centos-6-1.8

  build-leak-boringssl-static:
    image: netty:centos-6-1.8

  deploy:
    image: netty:centos-6-1.8

  shell:
    image: netty:centos-6-1.8
