version: "3"

services:

  runtime-setup:
    image: netty:centos-7-1.10
    build:
      args:
        centos_version : "7"
        java_version : "1.10-0"

  test:
    image: netty:centos-7-1.10

  test-boringssl-static:
    image: netty:centos-7-1.10

  shell:
    image: netty:centos-7-1.10
