name: PR Reports
on:
  workflow_run:
    workflows: [ "Build PR" ]
    types:
      - completed

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryhandler.count=5 -Dmaven.wagon.httpconnectionManager.ttlSeconds=240

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2.13.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: completed
          commit: ${{ github.event.workflow_run.head_commit.id }}
          # File location set in ci-pr.yml and must be coordinated.
          name: test-results-build
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1.0.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          commit: ${{ github.event.workflow_run.head_commit.id }}
          check_name: test reports
